CREATE SCHEMA IF NOT EXISTS PRUEBA;

CREATE SEQUENCE IF NOT EXISTS PRUEBA.PRICE_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PRUEBA.PRICES (
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST BIGINT DEFAULT NEXT VALUE FOR PRUEBA.PRICE_ID_SEQ PRIMARY KEY,
    PRODUCT_ID BIGINT,
    PRIORITY INTEGER,
    PRICE DECIMAL(10, 2),
    CURR VARCHAR(3)
);