CREATE SEQUENCE IF NOT EXISTS PRUEBA.USERS_ID_SQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PRUEBA.ROLES_ID_SQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PRUEBA.USERS (
    ID BIGINT DEFAULT NEXT VALUE FOR PRUEBA.USERS_ID_SQ PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN DEFAULT TRUE,
    ACCOUNT_NON_EXPIRED BOOLEAN DEFAULT TRUE,
    CREDENTIALS_NON_EXPIRED BOOLEAN DEFAULT TRUE,
    ACCOUNT_NON_LOCKED BOOLEAN DEFAULT TRUE,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PRUEBA.ROLES (
    ID BIGINT DEFAULT NEXT VALUE FOR PRUEBA.ROLES_ID_SQ PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PRUEBA.USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES PRUEBA.USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES PRUEBA.ROLES(ID)
);
