INSERT INTO PRUEBA.ROLES (NAME) VALUES ('ROLE_USER');
INSERT INTO PRUEBA.ROLES (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO PRUEBA.ROLES (NAME) VALUES ('ROLE_PRUEBA');

INSERT INTO PRUEBA.USERS (USERNAME, PASSWORD) VALUES ('prueba', '$2a$10$DOMDxjYyfZ/e7RcBfUpzqeaCs8pLgcizuiQWXPkU35nOhZlFcE9MS');--La clave es 12345

INSERT INTO PRUEBA.USER_ROLES (USER_ID, ROLE_ID)
VALUES (
    (SELECT ID FROM PRUEBA.USERS WHERE USERNAME = 'prueba'),
    (SELECT ID FROM PRUEBA.ROLES WHERE NAME = 'ROLE_PRUEBA')
);